S03 us03 1 offers unfiltered
WildCodeSchool/2023-03-JS-TLSE-P3-Externatic pull request #24
Opened 2023-07-11 10:23 UTC by Aeldro

2023-07-11 13:20 UTC, AnneClr approved these changes

2023-07-11 14:26 UTC, ArthurHtbk requested changes

2023-07-11 14:26 UTC, ArthurHtbk commented on backend/src/models/OfferManager.js
> +  findByFilters(keyword, localization, categories, contract) {
Un switch / case me paraît plus approprié ici !

2023-07-12 07:26 UTC, ArthurHtbk approved these changes

2023-07-12 07:26 UTC, merged