S05 alertsã management
WildCodeSchool/2023-03-JS-TLSE-P3-Externatic pull request #48
Opened 2023-07-25 14:03 UTC by Aeldro

2023-07-25 14:20 UTC, AnneClr approved these changes

2023-07-25 15:14 UTC, ArthurHtbk requested changes

2023-07-25 15:14 UTC, ArthurHtbk commented on backend/src/controllers/CompanyController.js
> +  // const namePattern = /^[a-zA-Z]/;
Je suis triste.

2023-07-26 07:56 UTC, Jasminegrz approved these changes

2023-07-26 08:00 UTC, ArthurHtbk approved these changes

2023-07-26 08:00 UTC, merged