Fixed responsive for pres
WildCodeSchool/2023-03-JS-TLSE-P3-Externatic pull request #8
Opened 2023-06-23 09:44 UTC by Aeldro

2023-06-23 09:44 UTC, AnneClr approved these changes

2023-06-23 09:51 UTC, aimach requested changes

2023-06-23 09:51 UTC, aimach commented on frontend/src/pages/MyProfile.jsx
> +                  checked={genre === "option1"}
remplacer par checked

2023-06-23 09:51 UTC, aimach commented on frontend/src/pages/MyProfile.jsx
> +                  checked={genre === "option2"}
enlève cette ligne

2023-06-23 09:51 UTC, aimach commented on frontend/src/pages/MyProfile.jsx
> +                  checked={genre === "option3"}
enlève cette ligne

2023-07-04 14:12 UTC, ArthurHtbk approved these changes

2023-07-04 14:13 UTC, merged